# Generated by Django 3.0.8 on 2020-08-03 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ktvwifi', '0003_complaint_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
