# Generated by Django 3.0.8 on 2020-08-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktvwifi', '0008_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
