# Generated by Django 3.0.8 on 2020-08-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktvwifi', '0009_auto_20200824_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lastname',
            new_name='subject',
        ),
    ]
