# Generated by Django 3.0.8 on 2020-08-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktvwifi', '0011_auto_20200825_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('o', 'Out for complaint'), ('c', 'Completed')], default='Pending', max_length=20),
        ),
    ]
