# Generated by Django 3.0.8 on 2020-08-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktvwifi', '0012_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Completed')], default='p', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
