# Generated by Django 3.0.8 on 2020-08-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktvwifi', '0013_auto_20200830_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
